# yaml-language-server: $schema=../../lang-config.json

grammar:
  project: https://github.com/microsoft/vscode
  version: 1.97.2
  files:
  - extensions/php/syntaxes/html.tmLanguage.json
  - extensions/php/syntaxes/php.tmLanguage.json

syntax:
  colors:
    comment.block.php: c0
    comment.line.double-slash.php: c0
    comment.line.number-sign.php: c0
    comment.line.shebang.php: c0
    keyword.control.break.php: p0
    keyword.control.case.php: p0
    keyword.control.continue.php: p0
    keyword.control.declare.php: p0
    keyword.control.default.php: p0
    keyword.control.die.php: p0
    keyword.control.do.php: p0
    keyword.control.else.php: p0
    keyword.control.elseif.php: p0
    keyword.control.enddeclare.php: p0
    keyword.control.endfor.php: p0
    keyword.control.endforeach.php: p0
    keyword.control.endif.php: p0
    keyword.control.endswitch.php: p0
    keyword.control.endwhile.php: p0
    keyword.control.exception.catch.php: p0
    keyword.control.exception.php: p0
    keyword.control.exit.php: p0
    keyword.control.for.php: p0
    keyword.control.foreach.php: p0
    keyword.control.goto.php: p0
    keyword.control.if.php: p0
    keyword.control.import.include.php: p0
    keyword.control.match.php: p0
    keyword.control.return.php: p0
    keyword.control.switch.php: p0
    keyword.control.while.php: p0
    keyword.control.yield-from.php: p0
    keyword.control.yield.php: p0
    keyword.definition.arrow.php: p0
    keyword.operator.arithmetic.php: p0
    keyword.operator.assignment.php: p0
    keyword.operator.bitwise.php: p0
    keyword.operator.class.php: p0
    keyword.operator.comparison.php: p0
    keyword.operator.error-control.php: p0
    keyword.operator.heredoc.php: s0
    keyword.operator.increment-decrement.php: p0
    keyword.operator.key.php: p0
    keyword.operator.logical.php: p0
    keyword.operator.nowdoc.php: s0
    keyword.operator.null-coalescing.php: p0
    keyword.operator.nullable-type.php: p0
    keyword.operator.return-value.php: p0
    keyword.operator.spread.php: p0
    keyword.operator.string.php: p0
    keyword.operator.ternary.php: p0
    keyword.operator.type.php: p0
    keyword.operator.variadic.php: p0
    keyword.other.clone.php: p0
    keyword.other.namespace.php: p0
    keyword.other.new.php: p0
    keyword.other.type.never.php: p0
    keyword.other.type.php: p0
    keyword.other.use-as.php: p0
    keyword.other.use-insteadof.php: p0
    keyword.other.use.php: p0
    meta.include.php punctuation.definition.string.begin.php: p0
    meta.include.php punctuation.definition.string.end.php: p0
    meta.include.php string.interpolated.php: p1
    meta.include.php string.quoted.double.php: p1
    meta.include.php string.quoted.single.php: p1
    punctuation.definition.arguments.begin.bracket.round.php: p0
    punctuation.definition.arguments.end.bracket.round.php: p0
    punctuation.definition.array.begin.bracket.round.php: p0
    punctuation.definition.array.end.bracket.round.php: p0
    punctuation.definition.arrow.php: p0
    punctuation.definition.begin.bracket.curly.php: p0
    punctuation.definition.begin.bracket.round.php: p0
    punctuation.definition.class.begin.bracket.curly.php: p0
    punctuation.definition.class.end.bracket.curly.php: p0
    punctuation.definition.end.bracket.curly.php: p0
    punctuation.definition.end.bracket.round.php: p0
    punctuation.definition.enum.begin.bracket.curly.php: p0
    punctuation.definition.enum.end.bracket.curly.php: p0
    punctuation.definition.interface.begin.bracket.curly.php: p0
    punctuation.definition.interface.end.bracket.curly.php: p0
    punctuation.definition.match-expression.begin.bracket.round.php: p0
    punctuation.definition.match-expression.end.bracket.round.php: p0
    punctuation.definition.namespace.begin.bracket.curly.php: p0
    punctuation.definition.namespace.end.bracket.curly.php: p0
    punctuation.definition.parameters.begin.bracket.round.php: p0
    punctuation.definition.parameters.end.bracket.round.php: p0
    punctuation.definition.section.match-block.begin.bracket.curly.php: p0
    punctuation.definition.section.match-block.end.bracket.curly.php: p0
    punctuation.definition.section.switch-block.begin.bracket.curly.php: p0
    punctuation.definition.section.switch-block.end.bracket.curly.php: p0
    punctuation.definition.string.begin.php: s0
    punctuation.definition.string.end.php: s0
    punctuation.definition.string.php: s0
    punctuation.definition.switch-expression.begin.bracket.round.php: p0
    punctuation.definition.switch-expression.end.bracket.round.php: p0
    punctuation.definition.trait.begin.bracket.curly.php: p0
    punctuation.definition.trait.end.bracket.curly.php: p0
    punctuation.definition.use.begin.bracket.curly.php: p0
    punctuation.definition.use.end.bracket.curly.php: p0
    punctuation.definition.variable.php: p0
    punctuation.section.array.begin.php: p0
    punctuation.section.array.end.php: p0
    punctuation.section.embedded.begin.php: p0
    punctuation.section.embedded.end.php source.php: p0
    punctuation.section.embedded.end.php: p0
    punctuation.separator.decimal.period.php: p0
    punctuation.separator.delimiter.php: p0
    punctuation.terminator.expression.php: p0
    punctuation.terminator.statement.php: p0
    source.php: p1
    storage.modifier.abstract.php: p0
    storage.modifier.extends.php: p0
    storage.modifier.final.php: p0
    storage.modifier.implements.php: p0
    storage.modifier.php: p0
    storage.modifier.reference.php: p0
    storage.type.class.php: p0
    storage.type.enum.php: p0
    storage.type.function.php: p0
    storage.type.interface.php: p0
    storage.type.trait.php: p0
    string.interpolated.php: s1
    string.quoted.double.php: s1
    string.quoted.single.php: s1
    string.regexp.double-quoted.php: s1
    string.regexp.single-quoted.php: s1
    string.unquoted.heredoc.php: s1
    string.unquoted.nowdoc.php: s1
    support.function.construct.output.php: p0
