# yaml-language-server: $schema=../../lang-config.json

grammar:
  project: https://github.com/microsoft/vscode
  version: 1.97.2
  files:
  - extensions/lua/syntaxes/lua.tmLanguage.json

syntax:
  colors:
    comment.block.lua: c0
    comment.line.double-dash.documentation.lua: c0
    comment.line.double-dash.lua: c0
    comment.line.shebang.lua: c0
    keyword.control.goto.lua: p0
    keyword.control.lua: p0
    keyword.local.lua: p0
    keyword.operator.lua: p0
    punctuation.definition.parameters.begin.lua: p0
    punctuation.definition.parameters.finish.lua: p0
    punctuation.definition.string.begin.lua: s0
    punctuation.definition.string.end.lua: s0
    punctuation.section.embedded.begin.lua: p0
    punctuation.section.embedded.end.lua: p0
    punctuation.separator.arguments.lua: p0
    source.lua: p1
    string.quoted.double.lua: s1
    string.quoted.other.multiline.lua: s1
    string.quoted.single.lua: s1
