# yaml-language-server: $schema=../../lang-config.json

grammar:
  project: https://github.com/bmalehorn/vscode-fish
  version: 2bdcfbea62cadc2a977eace3189d25b31df71e72
  files:
  - syntaxes/fish.tmLanguage.json

syntax:
  colors:
    comment.line.number-sign.fish: c0
    keyword.control.fish: p0
    punctuation.definition.string.begin.fish: s0
    punctuation.definition.string.end.fish: s0
    punctuation.definition.variable.fish: p0
    source.fish: p1
    string.quoted.double.fish: s1
    string.quoted.single.fish: s1
    variable.language.fish: p1
    variable.other.normal.fish: p1
