# yaml-language-server: $schema=../../lang-config.json

grammar:
  project: https://github.com/microsoft/vscode
  version: 1.97.2
  files:
  - extensions/yaml/syntaxes/yaml-1.0.tmLanguage.json
  - extensions/yaml/syntaxes/yaml-1.1.tmLanguage.json
  - extensions/yaml/syntaxes/yaml-1.2.tmLanguage.json
  - extensions/yaml/syntaxes/yaml-1.3.tmLanguage.json
  - extensions/yaml/syntaxes/yaml-embedded.tmLanguage.json
  - extensions/yaml/syntaxes/yaml.tmLanguage.json

syntax:
  colors:
    comment.line.number-sign.yaml: c0
    constant.language.merge.yaml: p0
    entity.name.tag.yaml: p1
    entity.other.document.begin.yaml: p0
    entity.other.document.end.yaml: p0
    keyword.control.flow.alias.yaml: p0
    keyword.control.flow.block-scalar.folded.yaml: p0
    keyword.control.flow.block-scalar.literal.yaml: p0
    keyword.control.property.anchor.yaml: p0
    meta.directive.yaml: p0
    punctuation.definition.block.sequence.item.yaml: p0
    punctuation.definition.key-value.begin.yaml: p0
    punctuation.definition.mapping.begin.yaml: p0
    punctuation.definition.mapping.end.yaml: p0
    punctuation.definition.sequence.begin.yaml: p0
    punctuation.definition.sequence.end.yaml: p0
    punctuation.definition.string.begin.yaml: s0
    punctuation.definition.string.end.yaml: s0
    punctuation.separator.key-value.mapping.yaml: p0
    punctuation.separator.mapping.yaml: p0
    punctuation.separator.sequence.yaml: p0
    source.yaml: s1
    storage.modifier.chomping-indicator.yaml: p0

test:
  # Skipping due to significant tokenization differences.
  skip: true
