# yaml-language-server: $schema=../../lang-config.json

extends: js

grammar:
  project: https://github.com/microsoft/vscode
  version: 1.97.2
  files:
  - extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json

syntax:
  replace:
    .js: .ts
