# yaml-language-server: $schema=../../lang-config.json

grammar:
  project: https://github.com/microsoft/vscode
  version: 1.97.2
  files:
  - extensions/sql/syntaxes/sql.tmLanguage.json

syntax:
  colors:
    comment.line.double-dash.sql: c0
    keyword.operator.comparison.sql: p0
    keyword.operator.concatenator.sql: p0
    keyword.operator.math.sql: p0
    keyword.other.alias.sql: p0
    keyword.other.authorization.sql: p0
    keyword.other.create.sql: p0
    keyword.other.data-integrity.sql: p0
    keyword.other.DDL.create.II.sql: p0
    keyword.other.DML.II.sql: p0
    keyword.other.DML.sql: p0
    keyword.other.LUW.sql: p0
    keyword.other.order.sql: p0
    keyword.other.sql: p0
    punctuation.definition.string.begin.sql: s0
    punctuation.definition.string.end.sql: s0
    punctuation.section.scope.begin.sql: p0
    punctuation.section.scope.end.sql: p0
    source.sql comment.block: c0
    source.sql: p1
    storage.modifier.sql: p0
    storage.type.sql: p0
    string.quoted.double.sql: s1
    string.quoted.single.sql: s1
