# yaml-language-server: $schema=../../lang-config.json

grammar:
  project: https://github.com/microsoft/vscode
  version: 1.97.2
  files:
  - extensions/docker/syntaxes/docker.tmLanguage.json

syntax:
  colors:
    comment.line.number-sign.dockerfile: c0
    keyword.control.dockerfile: p0
    keyword.other.special-method.dockerfile: p0
    source.dockerfile: p1
